language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install -r requirements.txt
  - python setup.py develop
script: python setup.py test
env:
  global:
    - secure: "XfY0mfudQyyl27D5pgmJCtvkZNTvwCkHx2/Bt5EuKZALK2WUBGbxAM2hSB5hxlTVeZw+cUkCXDTpLOK03CslYun2p7H9yc2rUlhvBalF5cVu6OcGxK4OvuUCWyRngmsUpoIhzCfSkUBtFVQDXsLCs+ORpv0U2Po2oW59cWynEX4="
    - secure: "B5zXLej96h7rdk5kxsFO8eLO2m8eNH/h87MMLuiNVW0AvIfvbS8gNbbzIHY1M4ZgMnEZT4JWpMi2o+W0Dog7tSxmYJjHTJt6777vYUrBfzR2NZe+6C0gJ7F2AlVTki+fdk0RbPDe0GzI83F3w5TwmyEdSWTvH9ZGfstIw91hk+U="
